from typing import TypedDict, Optional, List, Annotated
from enum import Enum
from pydantic import BaseModel

# class GraphState(TypedDict):
#     """Represents the state of our graph."""
#     problem_data: dict          # The current question, options, answer, etc. (like your problem_dict)
#     topic: Enum                 # The desired Topic (e.g., Topic.INFORMATION_AND_IDEAS)
#     difficulty: Enum            # The desired Difficulty (e.g., Difficulty.HARD)
#     status: QuestionStatus      # Current status of the question (for conditional routing)
#     generation_attempts: int    # Counter for retry limit
#     feedback_history: List[str] # Stores feedback from the Review Agent
#     raw_passage: str            # NEW: Stores the text generated by the Passage Agent
#     Question_type: List[str]
#     n_Questions_to_rewrite: int


class GraphState(TypedDict):
    raw_passage: str        
    status: str   
    question_type: str 
    Question_info: Optional[dict]
    feedback: Optional[str]
    difficulty:str
    iterations:int
    validator_feedback:Optional[str]

   

class QuestionStatus(Enum):
    GENERATED = "generated"
    QUESTIONS_GENERATED="questions_generated"
    PASSAGE_REDO='Passage_Redo'
    REFINED='Refined'
    INITIALISED="Initialised"
    VALIDATED = "validated"
    FAILED_VALIDATION = "failed_validation"
    # FAILED_REVIEW = "failed_review"
    # PASSED_FINAL = "passed_final"
    FAILED="Failed"
    REVIEW_SUCCESS="review_success"

